#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     conveyor1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     conveyor2,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    sweeper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    clipper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows ("joystickGame")
#include "JoystickDriver.c"

task main()
{
while(1==1)
{
	motor[right]=joystick.joy1_y2/1.3;
	motor[left]=-joystick.joy1_y1/1.3;

if(joystick.joy1_y1<8 && joystick.joy1_y1>-8)
{
	motor[left]=0;
}
if(joystick.joy1_y2<8 && joystick.joy1_y2>-8)
{
	motor[right]=0;
}



if(joy2Btn(8)==1)
{
	motor[lift1]=25;
	motor[lift2]=-25;
}
if(joy2Btn(7)==1)
{
	motor[lift1]=-25;
	motor[lift2]=25;
}
if(joy2Btn(8)==0 && joy2Btn(7)==0)
{
	motor[lift1]=0;
	motor[lift2]=0;
}




if(joy2Btn(6)==1)
{
	motor[conveyor1]=-20;
	motor[conveyor2]=20;
}
if(joy2Btn(5)==1)
{
	motor[conveyor1]=20;
	motor[conveyor2]=-20;
}
if(joy2Btn(5)==0 && joy2Btn(6)==0)
{
	motor[conveyor1]=0;
	motor[conveyor2]=0;
}



if(joy2Btn(10)==1)
{
	servo[clipper]=230;
}
if(joy2Btn(9)==1)
{
	servo[clipper]=20;
}



if(joy2Btn(3)==1)
{
	servo[sweeper]=256;
}
if(joy2Btn(1)==1)
{
	servo[sweeper]=0;
}
if(joy2Btn(2)==1)
{
	servo[sweeper]=117;
}
}
}
