#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void ClipperDown()
 {
   servo [servo2]= 2;						//functions to set up servo motors
 }

 void ClipperUp()
 {
   servo[servo2]= 245;
 }

task main()
{

ClipperUp();
wait1Msec(800);

motor[motorD]= -48;
motor[motorE]= -40;
wait1Msec(6000); 		//drives out of parking zone toward rolling goals

motor[motorD]= 0;
motor[motorE]= 0;
wait1Msec(100);			//stop

motor[motorF]= 42;
motor[motorG]= 42;
wait1Msec(3100);   		//lift up

motor[motorF]= 0;
motor[motorG]= 0;
wait1Msec(100);

ClipperDown() ;
wait1Msec(1000);		//clipper clips onto rolling goal

motor[motorH]= 18;
motor[motorI]= 18;
wait1Msec(3100);			//conveyor moving up


motor[motorH]= 0;
motor[motorI]= 0;
wait1Msec(1500);			//conveyor resting


motor[motorH]= -10;
motor[motorI]= -10;
wait1Msec(500);			//conveyor moving down

motor[motorF]= -35;
motor[motorG]= -35;
wait1Msec(2200);   		//lift down

motor[motorF]= 0;
motor[motorG]= 0;
wait1Msec(100);





ClipperUp() ;
wait1Msec(1000);		//clipper releases rolling goal and prepares for Teleop

}
